name: NODE 설치

on:
  push:
    branches:
      - development

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 브랜치
        uses: actions/checkout@v2

      - name: Node.js 설치
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start Nest.js with PM2
        run: |
          npm install -g pm2
          pm2 delete main || true
          pm2 start ecosystem.config.js
